### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by chentsulin**

### CODE REVIEW

**Comment by taion** [comment]
The build seems to be failing here.

**Comment by chentsulin** [comment]
`npm i -D sinon@2.0.0-pre.4` will fix the tests, but cause peer dependencies errors.

```
npm WARN karma-sinon-chai@1.2.4 requires a peer of sinon@^1.17.2 but none was installed.
npm WARN sinon-chai@2.8.0 requires a peer of sinon@>=1.4.0 <2 but none was installed.
npm ERR! code 1
```

**Comment by taion** [comment]
oh – don't actually import `sinon` in the tests. `karma-sinon-chai` adds `sinon` as a global that you can just use. if you just drop the imports it will be fine i think

**Comment by chentsulin** [comment]
Thanks for the tips, it passed!

**Pull request merged**
